CREATE TABLE if not exists Mapset (
    id INTEGER PRIMARY KEY, 
    creator_id INTEGER, 
    creator_username VARCHAR(255), 
    creator_avatar_url TEXT, 
    artist VARCHAR(255), 
    title VARCHAR(255), 
    source VARCHAR(255), 
    tags TEXT, 
    description TEXT, 
    date_submitted DATE, 
    date_last_updated DATE, 
    ranking_queue_status INTEGER, 
    ranking_queue_last_updated DATE, 
    ranking_queue_vote_count INTEGER, 
    mapset_ranking_queue_id INTEGER
);

CREATE TABLE if not exists Map (
    id INTEGER PRIMARY KEY, 
    mapset_id INTEGER,
    md5 TEXT, 
    alternative_md5 TEXT, 
    creator_id INTEGER, 
    creator_username TEXT, 
    game_mode INTEGER, 
    ranked_status INTEGER, 
    artist TEXT, 
    title TEXT, 
    source TEXT, 
    tags TEXT, 
    description TEXT, 
    difficulty_name TEXT, 
    length INTEGER, 
    bpm INTEGER, 
    difficulty_rating REAL, 
    count_hitobject_normal INTEGER, 
    count_hitobject_long INTEGER, 
    play_count INTEGER, 
    fail_count INTEGER, 
    mods_pending INTEGER, 
    mods_accepted INTEGER, 
    mods_denied INTEGER, 
    mods_ignored INTEGER, 
    online_offset INTEGER, 
    clan_ranked INTEGER,
    FOREIGN KEY (mapset_id) REFERENCES Mapset(id)
);